#!/bin/bash

# 🎯 INSTRUCCIONES DE USO - DEVSHOUSE SERVICES

echo "╔════════════════════════════════════════════════════════════╗"
echo "║          🚀 DEVSHOUSE - SERVICIOS EN FUNCIONAMIENTO       ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ ESTADO ACTUAL:"
echo "  • Backend:  http://localhost:3001 ✓"
echo "  • Frontend: http://localhost:5173 ✓"
echo "  • Base de Datos: PostgreSQL AWS RDS ✓"
echo "  • Monitor de Servicios: ACTIVO ✓"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "📊 VERIFICAR CONECTIVIDAD:"
echo ""
echo "  Backend + BD:"
echo "    $ curl http://localhost:3001/api/health"
echo ""
echo "  Frontend:"
echo "    $ curl http://localhost:5173/"
echo ""
echo "  Ambos:"
echo "    $ sleep 3 && curl -s http://localhost:3001/api/health && echo '' && curl -s http://localhost:5173/ | head -5"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "📋 VER LOGS EN TIEMPO REAL:"
echo ""
echo "  Backend:"
echo "    $ tail -f /tmp/backend.log"
echo ""
echo "  Frontend:"
echo "    $ tail -f /tmp/frontend.log"
echo ""
echo "  Monitor de Servicios:"
echo "    $ tail -f /tmp/monitor.log"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "🔄 MONITOREO AUTOMÁTICO:"
echo ""
echo "  ✓ Se reinicia automáticamente cada 10 segundos"
echo "  ✓ Detecta si Backend o Frontend se caen"
echo "  ✓ Se reinician automáticamente sin intervención"
echo "  ✓ Base de datos siempre conectada"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "🛑 PARA DETENER SERVICIOS:"
echo ""
echo "  Opción 1 (Recomendado - Limpio):"
echo "    $ pkill -f 'monitor-services.sh'"
echo ""
echo "  Opción 2 (Fuerza):"
echo "    $ pkill -9 npm; pkill -9 node"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "🔧 REINICIAR SERVICIOS:"
echo ""
echo "  $ nohup bash /Users/ibacrea/Documents/devshouse-/monitor-services.sh > /tmp/monitor.log 2>&1 &"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "🗂️  INFORMACIÓN IMPORTANTE:"
echo ""
echo "  Scripts:"
echo "    • /Users/ibacrea/Documents/devshouse-/monitor-services.sh"
echo "    • /Users/ibacrea/Documents/devshouse-/start-services.sh"
echo ""
echo "  Documentación:"
echo "    • /Users/ibacrea/Documents/devshouse-/SERVICES-MONITOR.md"
echo ""
echo "  Configuración Frontend ↔ Backend:"
echo "    • /Users/ibacrea/Documents/devshouse-/frontend/src/config/constants.js"
echo "    • BASE_URL: http://localhost:3001/api"
echo ""
echo "  Configuración Backend ↔ BD:"
echo "    • /Users/ibacrea/Documents/devshouse-/backend/.env"
echo "    • BD_HOST: ibacrea-postgres-db.cxue6u0qsdft.us-east-1.rds.amazonaws.com"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "✨ ¡Sistema funcionando correctamente!"
echo ""
